use std::sync::atomic::AtomicUsize;

use crate::{
    codegen::{FunctionArgumentIdentifier, StructAttributes},
    error::{parser::ParserError, syntax::SyntaxError},
    parser::{common::ParsedTokenInstance, function::PathMap},
    tokenizer::Token,
    ty::{OrdMap, Type},
};
use strum_macros::Display;

#[derive(Debug, Clone, Display, PartialEq, Eq, Hash)]
pub enum ControlFlowType
{
    Break,
    Continue,
}

pub type UniqueId = usize;

/// Wrapper (around [`AtomicUsize`]) [`IdSource`] type.
/// [`AtomicUsize`] with a simplified function interface.
#[derive(Debug)]
pub struct IdSource
{
    inner: AtomicUsize,
}

impl IdSource
{
    /// Creates a new [`IdSource`] with a starting id.
    pub const fn new(starting_id: usize) -> Self
    {
        Self {
            inner: AtomicUsize::new(starting_id),
        }
    }

    /// Fetches current [`AtomicUsize`] state and increments it by one.
    pub fn get_unique_id(&self) -> UniqueId
    {
        self.inner
            .fetch_add(1, std::sync::atomic::Ordering::Relaxed)
    }

    /// Sets the current internal state of the [`IDSource`].
    pub fn set_current_unique_id(&self, id: UniqueId)
    {
        self.inner.store(id, std::sync::atomic::Ordering::Relaxed);
    }

    /// Fetches the current state of the internal [`AtomicUsize`].
    pub fn get_current_id(&self) -> usize
    {
        self.inner.load(std::sync::atomic::Ordering::Relaxed)
    }
}

/// This static is a Variable Id source. This means that all of the variables (function argmuents included) have a unqiue id generated by this function.
/// This is crucial when implementing a pre allocation table for loops
pub static VARIABLE_ID_SOURCE: IdSource = IdSource::new(0);

#[derive(Debug, Clone, Display, PartialEq, Eq, Hash, strum_macros::EnumTryAs)]
/// VariableReferences are the lowest layer of referencing a variable. This is enum wrapped in a ParsedToken, consult the documentation of that enum variant for more information.ű
/// VariableReferences should not contain themselves as they are only for referencing a variable, there is not much more to it.
pub enum VariableReference
{
    /// Struct field reference
    StructFieldReference(StructFieldRef),
    /// Variable name and custom identifier number (in current scope)
    BasicReference(String, usize),
    /// Variable name, array index
    ArrayReference(ArrayIndexing),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StructFieldRef
{
    /// Variable reference enum this shows the underlying variable its referring from
    pub variable_ref: Box<VariableReference>,
    /// This field is for verifying types (Even if the struct fields match it could still be two different structs)
    pub struct_name: String,
    /// The actual struct body, this contains the fields paired with their types. (In order of insertion)
    /// This field uses an [`OrdMap`] so that [`Hash`] can be implemented.
    pub struct_fields: OrdMap<String, Type>,
    /// This is the fields name we are refering
    pub field: StructFieldType<
        String,
        (
            FunctionSignature,
            OrdMap<
                FunctionArgumentIdentifier<String, usize>,
                (ParsedTokenInstance, (Type, UniqueId)),
            >,
        ),
    >,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum StructFieldType<F, FN>
{
    Field(F),
    Function(FN),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ArrayIndexing
{
    pub variable_reference: Box<VariableReference>,
    pub idx: Box<ParsedTokenInstance>,
}

/// The first item of the StructFieldReference is used to look up the name of the variable which stores the Struct.
/// The functions which take the iterator of the `field_stack` field should not be passed the first item of the iterator, since the first item is used to look up the name of the variable which stores the struct.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StructFieldReference
{
    /// The name of the fields which get referenced
    pub field_stack: Vec<String>,
}

impl Default for StructFieldReference
{
    fn default() -> Self
    {
        Self::new()
    }
}

impl StructFieldReference
{
    /// Creates an instnace from a single entry
    pub fn from_single_entry(field_name: String) -> Self
    {
        Self {
            field_stack: vec![field_name],
        }
    }

    /// Initializes an instance from a list of field entries
    pub fn from_stack(field_stack: Vec<String>) -> Self
    {
        Self { field_stack }
    }

    /// Creates an instnace from an empty list
    pub fn new() -> Self
    {
        Self {
            // Most struct references are one field deep, might aswell take a guess
            field_stack: Vec::with_capacity(1),
        }
    }
}

/// Parses the tokens passed in and stores the field names into [`StructFieldReference`].
/// This function returns the last field's type.
/// When the function returns a [`StructFieldType::Function`] the var_ref will point to the last [`StructFieldType::Field`]. The reason is that we do not modify `var_ref` here, to avoid having to pass in a bunch of arguments.
/// If we really wanted to parse it and return the correct `var_ref` we would need to greatly clutter the arguments list.
/// Please keep this little discrepancy in mind.
pub fn get_struct_field(
    tokens: &[Token],
    token_idx: &mut usize,
    identifier: &str,
    module_path: Vec<String>,
    (struct_name, struct_fields, attributes): &(String, OrdMap<String, Type>, StructAttributes),
    var_ref: &mut VariableReference,
) -> anyhow::Result<StructFieldType<Type, (usize, UnparsedFunctionDefinition)>>
{
    // dbg!(&attributes);
    // Match field name
    if let Some(Token::Identifier(field_name)) = tokens.get(*token_idx) {
        // Lookup struct field
        // If it is not a struct but is a some store the struct field name and return
        if let Some(field_type) = struct_fields.get(field_name) {
            // Store field name
            *var_ref = VariableReference::StructFieldReference(StructFieldRef {
                variable_ref: Box::new(var_ref.clone()),
                struct_name: struct_name.clone(),
                struct_fields: struct_fields.clone(),
                field: StructFieldType::Field(field_name.clone()),
            });

            *token_idx += 1;

            // Match syntax
            if let Some(Token::Dot) = tokens.get(*token_idx) {
                *token_idx += 1;

                let next_struct_def = field_type
                    .try_as_struct_ref()
                    .ok_or(ParserError::TypeWithoutFields(field_type.clone()))?;

                // Call this function once again and iterate
                get_struct_field(
                    tokens,
                    token_idx,
                    identifier,
                    module_path,
                    next_struct_def,
                    var_ref,
                )
            }
            else {
                // Return field type
                Ok(StructFieldType::Field(field_type.clone()))
            }
        }
        // If a function was implemented with this name and it was referenced here we should parse the function call
        // This means that there is a receiver in the function def ie `this`
        else if let Some(impl_fn) = attributes.impl_fn_list.get(field_name) {
            // This unwrap is safe here since everything is being parsed
            // If code gets changed later this will invertedly panic
            let impl_fn = impl_fn.try_as_unparsed_ref().unwrap();

            // Return the function's name we will parse it later, not here (to avoid having to add 1000 arguments to this function too)
            Ok(StructFieldType::Function((
                impl_fn.token_offset,
                impl_fn.clone(),
            )))
        }
        else {
            Err(ParserError::SyntaxError(SyntaxError::StructFieldNotFound(
                field_name.clone(),
                struct_name.clone(),
            ))
            .into())
        }
    }
    else {
        Err(ParserError::SyntaxError(SyntaxError::InvalidStructFieldReference).into())
    }
}

use std::{collections::HashMap, rc::Rc};

use crate::{
    anyhow::Result,
    codegen::CustomItem,
    error::SpanInfo,
    indexmap::IndexMap,
    parser::{
        common::ParsedToken,
        dbg::fetch_and_merge_debug_information,
        function::{FunctionSignature, UnparsedFunctionDefinition},
        value::MathematicalSymbol,
    },
};

use crate::parser::value::parse_token_as_value;

/// This function parses the tokens after a variable.
/// This function parses actions related to variables. Such as: `var + 5` and `var =% 3`, etc.
/// TODO: Make this fn have a side effect on `var_ref` and just wrap the value into a parsed token instance at the end
pub fn resolve_variable_expression(
    _tokens: &[Token],
    // Token slice offset, this allows us to keep the correct slice indexing (without ruining token_idx)
    _function_token_offset: usize,
    _debug_infos: &[SpanInfo],
    _token_idx: &mut usize,
    _function_signatures: Rc<PathMap<Vec<String>, String, UnparsedFunctionDefinition>>,
    _function_imports: Rc<HashMap<String, FunctionSignature>>,
    _variable_scope: &mut IndexMap<String, (Type, UniqueId)>,
    (_variable_type, _variable_id): (Type, UniqueId),
    _custom_items: Rc<IndexMap<String, CustomItem>>,
    _variable_ref: &mut ParsedTokenInstance,
    _parsed_tokens: &mut Vec<ParsedTokenInstance>,
    _variable_name: &str,
    _module_path: Vec<String>,
) -> Result<Type>
{
    Ok(todo!())
}

pub fn set_value_math_expr(
    tokens: &[Token],
    token_offset: usize,
    debug_infos: &[SpanInfo],
    function_signatures: Rc<PathMap<Vec<String>, String, UnparsedFunctionDefinition>>,
    token_idx: &mut usize,
    variable_scope: &mut IndexMap<String, (Type, UniqueId)>,
    variable_type: Type,
    variable_reference: &mut ParsedTokenInstance,
    math_symbol: MathematicalSymbol,
    standard_function_table: Rc<HashMap<String, FunctionSignature>>,
    custom_items: Rc<IndexMap<String, CustomItem>>,
    module_path: Vec<String>,
) -> Result<()>
{
    let origin_token_idx = *token_idx;

    *token_idx += 1;

    let eval_token = tokens.get(*token_idx).ok_or(ParserError::SyntaxError(
        SyntaxError::InvalidVariableDefinition,
    ))?;

    let (next_token, _ty) = parse_token_as_value(
        tokens,
        token_offset,
        debug_infos,
        origin_token_idx,
        function_signatures,
        variable_scope,
        Some(variable_type.clone()),
        token_idx,
        eval_token,
        standard_function_table,
        custom_items.clone(),
        module_path.clone(),
    )?;

    *variable_reference = ParsedTokenInstance {
        inner: ParsedToken::SetValue(
            Box::new(variable_reference.clone()),
            Box::new(ParsedTokenInstance {
                inner: ParsedToken::MathematicalExpression(
                    Box::new(variable_reference.clone()),
                    math_symbol,
                    Box::new(next_token),
                ),
                debug_information: fetch_and_merge_debug_information(
                    debug_infos,
                    origin_token_idx + token_offset..*token_idx + token_offset,
                    true,
                )
                .unwrap(),
            }),
        ),
        debug_information: fetch_and_merge_debug_information(
            debug_infos,
            origin_token_idx + token_offset..*token_idx + token_offset,
            true,
        )
        .unwrap(),
    };

    Ok(())
}
