use std::sync::atomic::AtomicUsize;

use crate::{
    codegen::{FunctionArgumentIdentifier, StructAttributes},
    error::{Spanned, parser::ParserError, syntax::SyntaxError},
    parser::{
        common::StatementVariant,
        function::{FunctionSignature, PathMap},
    },
    tokenizer::Token,
    ty::{OrdMap, Type},
};
use strum_macros::Display;

#[derive(Debug, Clone, Display, PartialEq, Eq, Hash)]
pub enum ControlFlowType
{
    Break,
    Continue,
}

pub type UniqueId = usize;

/// Wrapper (around [`AtomicUsize`]) [`IdSource`] type.
/// [`AtomicUsize`] with a simplified function interface.
#[derive(Debug)]
pub struct IdSource
{
    inner: AtomicUsize,
}

impl IdSource
{
    /// Creates a new [`IdSource`] with a starting id.
    pub const fn new(starting_id: usize) -> Self
    {
        Self {
            inner: AtomicUsize::new(starting_id),
        }
    }

    /// Fetches current [`AtomicUsize`] state and increments it by one.
    pub fn get_unique_id(&self) -> UniqueId
    {
        self.inner
            .fetch_add(1, std::sync::atomic::Ordering::Relaxed)
    }

    /// Sets the current internal state of the [`IDSource`].
    pub fn set_current_unique_id(&self, id: UniqueId)
    {
        self.inner.store(id, std::sync::atomic::Ordering::Relaxed);
    }

    /// Fetches the current state of the internal [`AtomicUsize`].
    pub fn get_current_id(&self) -> usize
    {
        self.inner.load(std::sync::atomic::Ordering::Relaxed)
    }
}

/// This static is a Variable Id source. This means that all of the variables (function argmuents included) have a unique id generated by this function.
/// This is crucial when implementing a pre allocation table for loops
pub static VARIABLE_ID_SOURCE: IdSource = IdSource::new(0);

#[derive(Debug, Clone, Display, PartialEq, Eq, Hash, strum_macros::EnumTryAs)]
/// VariableReferences are the lowest layer of referencing a variable. This enum wrapped in a ParsedToken, consult the documentation of that enum variant for more information.
/// VariableReferences should not contain themselves as they are only for referencing a variable, there is not much more to it.
pub enum VariableReference
{
    /// Variable name and custom identifier number (id for global scope)
    BasicReference
    {
        /// The referred variable's name
        variable_name: String,
        // The referred variables global id
        // id: usize
    },
    ///
    StructField
    {
        /// Inner reference for the underlying variable
        inner_reference: Box<Spanned<VariableReference>>,
        /// The field name we are trying to access
        field_name: String,
    },
    ArrayIndex
    {
        /// Inner reference for the underlying variable
        inner_reference: Box<Spanned<VariableReference>>,
        /// The index we are trying to access through the variable
        index: Box<Spanned<StatementVariant>>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StructFieldRef
{
    /// Variable reference enum this shows the underlying variable its referring from
    pub variable_ref: Box<VariableReference>,
    /// This field is for verifying types (Even if the struct fields match it could still be two different structs)
    pub struct_name: String,
    /// The actual struct body, this contains the fields paired with their types. (In order of insertion)
    /// This field uses an [`OrdMap`] so that [`Hash`] can be implemented.
    pub struct_fields: OrdMap<String, Type>,
    /// This is the fields name we are refering
    pub field: StructFieldType<
        String,
        (
            FunctionSignature,
            OrdMap<
                FunctionArgumentIdentifier<String, usize>,
                (Spanned<StatementVariant>, (Type, UniqueId)),
            >,
        ),
    >,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum StructFieldType<F, FN>
{
    Field(F),
    Function(FN),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ArrayIndexing
{
    pub variable_reference: Box<VariableReference>,
    pub idx: Box<Spanned<StatementVariant>>,
}

/// The first item of the StructFieldReference is used to look up the name of the variable which stores the Struct.
/// The functions which take the iterator of the `field_stack` field should not be passed the first item of the iterator, since the first item is used to look up the name of the variable which stores the struct.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StructFieldReference
{
    /// The name of the fields which get referenced
    pub field_stack: Vec<String>,
}

impl Default for StructFieldReference
{
    fn default() -> Self
    {
        Self::new()
    }
}

impl StructFieldReference
{
    /// Creates an instnace from a single entry
    pub fn from_single_entry(field_name: String) -> Self
    {
        Self {
            field_stack: vec![field_name],
        }
    }

    /// Initializes an instance from a list of field entries
    pub fn from_stack(field_stack: Vec<String>) -> Self
    {
        Self { field_stack }
    }

    /// Creates an instnace from an empty list
    pub fn new() -> Self
    {
        Self {
            // Most struct references are one field deep, might aswell take a guess
            field_stack: Vec::with_capacity(1),
        }
    }
}
