[package]
name = "fog-lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = {default-features = false, version = "0.2.172"}

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
