[package]
name = "fog-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
fog-common = { path = "../common" }
fog-codegen = { path = "../codegen" }
fog-parser = { path = "../parser" }
serde = { version = "1.0.228", features = ["derive"] }
fog-imports = { path = "../imports" }